---

- name: Available nodes
  hosts: available_nodes
  vars_files:
    - config.yml
  roles:
    - role: common

- name: Control nodes
  hosts: control_nodes
  vars_files:
    - config.yml
  roles:
    - role: control
