---
- name: Start iperf3 servers.
  hosts: iperf_grp_a
  tasks:
    - name: Run iperf3 servers.
      ansible.builtin.command:
        cmd: iperf3 --server --daemon --one-off
      changed_when: false

- name: Run iperf3 clients
  hosts: iperf_grp_b
  serial: 100%
  tasks:
    - name: Determine iperf3 parameters.
      ansible.builtin.set_fact:
        iperf_server: "{{ groups['iperf_grp_a'][groups['iperf_grp_b'].index(inventory_hostname)] }}"
    - name: Determine iperf3 result output filename.
      ansible.builtin.set_fact:
        iperf_out: "iperf3_{{ ansible_date_time.iso8601_basic_short }}_{{ inventory_hostname }}_{{ iperf_server }}.out"
    - name: Run iperf3 client.
      ansible.builtin.shell:
        cmd: "iperf3 --client {{ iperf_server }} >> {{ iperf_out }}"
      changed_when: false
    - name: Grab iperf3 output.
      ansible.builtin.fetch:
        src: "{{ iperf_out }}"
        dest: results/iperf3/
        flat: true
    - name: Delete output.
      ansible.builtin.file:
        path: "{{ iperf_out }}"
        state: absent

- name: Start iperf3 servers.
  hosts: iperf_grp_b
  tasks:
    - name: Run iperf3 servers.
      ansible.builtin.command:
        cmd: iperf3 --server --daemon --one-off
      changed_when: false

- name: Run iperf3 clients
  hosts: iperf_grp_a
  serial: 100%
  tasks:
    - name: Determine iperf3 parameters.
      ansible.builtin.set_fact:
        iperf_server: "{{ groups['iperf_grp_b'][groups['iperf_grp_a'].index(inventory_hostname)] }}"
    - name: Determine iperf3 result output filename.
      ansible.builtin.set_fact:
        iperf_out: "iperf3_{{ ansible_date_time.iso8601_basic_short }}_{{ inventory_hostname }}_{{ iperf_server }}.out"
    - name: Run iperf3 client.
      ansible.builtin.shell:
        cmd: "iperf3 --client {{ iperf_server }} >> {{ iperf_out }}"
      changed_when: false
    - name: Grab iperf3 output.
      ansible.builtin.fetch:
        src: "{{ iperf_out }}"
        dest: results/iperf3/
        flat: true
    - name: Delete output.
      ansible.builtin.file:
        path: "{{ iperf_out }}"
        state: absent
